### ISSUE TITLE
How could I port the python1300 design to Vivado 2015.4?

### ISSUE THREAD

**Issue by ProfFan** [Avnet/hdl#1]
Hi,

I am currently trying to port the design to Vivado 2015.4, but it does not support the tpg 6.0 core. The new TPG core only has one clock input. What should I do?

**Comment by zedman2000** [comment]
@ProfFan I've asked @AlbertaBeef to let you know what the status is.

**Comment by ProfFan** [comment]
@zedman2000 Thank you very much :)

**Comment by AlbertaBeef** [comment]
@ProfFan,

To answer your question, the clock that was used for the AXI4-Lite interface has been removed.  The new TPG core now only uses one clock, which is the clock for the video data path.
Please take a look at microzed.org for the new version of the design.
For MicroZed Embedded Vision Kit + PYTHON :
   http://microzed.org/sites/default/files/design/EMBV_HDMI_Passthrough_Tutorial_2015_4_01.zip 
For FMC-HDMI-CAM + PYTHON :
   http://zedboard.org/sites/default/files/design/FMCHC_PYTHON1300C_Tutorial_2015_4_01.zip
Regards,
Mario.

**Comment by ProfFan** [comment]
Got it, thanks.
