### ISSUE TITLE
pzfmc2 HDMI make error 

### ISSUE THREAD

**Issue by kushalcAgiliad** [Avnet/hdl#11]
Hi,
I am trying to make the design pzfmc2 hdmi design on vivado 2017.4 with the help of "make_pzfmc2_hdmi.tcl", after running this tcl file it gives me error 

ERROR: [Board 49-71] The board_part definition was not found for em.avnet.com:picozed_7030:part0:1.0. The project's board_part property was not set, but the project's part property was set to xc7z030sbg485-1. Valid board_part values can be retrieved with the 'get_board_parts' Tcl command. Check if board.repoPaths parameter is set and the board_part is installed from the tcl app store.

    while executing
"source ./ProjectScripts/$project.tcl -notrace"
    ("PZ7030_FMC2" arm line 2)
    invoked from within
"switch -nocase $board {
   PZ7015_FMCCC               -
   PZ7030_FMCCC               -
   PZ7010_FMC2                -
   PZ7020_FMC2                ..."
    (file "./make.tcl" line 306)

    while executing
"source ./make.tcl -notrace"
    (file "./make_pzfmc2_hdmi.tcl" line 51)

I have down loaded the latest 2017.4 bdf from "https://github.com/Avnet/bdf" and added them to the folder "Xilinx/Vivado/2017.4/data/boards/board_files"

Not able to figure out the issue, Please help me to resolve this issue.

**Comment by dss91** [comment]
same problem,
in my case i try to run the command ./source/create_project to create  vivado project which causes the same error of baord file

**Comment by zedhed** [comment]
Hi @kushalcAgiliad and @dss91 

What tutorial are you following for this?

The best place to post questions is on the PicoZed support forums that are monitored by Avnet engineering and support teams:

http://picozed.org/forums/zed-english-forum

Best Regards,

-Kevin
