### ISSUE TITLE
Scripts filename case sensitive

### ISSUE THREAD

**Issue by TheNiceGuy** [Avnet/hdl#12]
Thanks for providing these well done scripts. I assume these have been tested on Windows (filesystem is case insensitive). That said, when running `source make_minized_foundation.tcl` on Linux, I got

```
...
couldn't read file "../Boards/minized/minized.tcl": no such file or directory
...
```

The actual folder is `../Boards/MINIZED/MINIZED.tcl`. Renaming the path to `../Boards/minized/minized.tcl` fixed it.

**Comment by zedhed** [comment]
Thank you @TheNiceGuy for pointing this out!  We will schedule for this to get fixed in the next release so that at least it gets fixed within HEAD.

**Comment by aborodin** [comment]
> it gets fixed within HEAD.

This issue is still actual, especially on Linux.

>vivado -mode tcl -source make_pzsdr_p13c.tcl
>[skip]
>Setting Up Project pzsdr_p13c...
>***** Generating IP...
>***** Creating Vivado Project...
>couldn't read file "../Boards/PZSDR7035_FMCCC/pzsdr7035_fmccc.tcl": no such file or directory
>    while executing
>"source ../Boards/$board/[string tolower $board].tcl -notrace"
>    (file "./ProjectScripts/pzsdr_p13c.tcl" line 108)
>[skip]
