### ISSUE TITLE
New Vivado IP cores doesn't compatible with old designs

### ISSUE THREAD

**Issue by bwang40** [Avnet/hdl#2]
In the newest version of this repository, the IP core is generated with the newer version of the VIVADO. However, some of the project for example FMCCH are only compatible with VIVADO 2015.4, which is not able to read the new IP core. I  have to get back to the old version of the ipcore to get your reference design work. Please fix it, it is confusing.

**Comment by narrucmot** [comment]
Can you be specific about what project you are trying to build?

**Comment by bwang40** [comment]
Fmcch, there are 3 of them. I get it work by using the old ip cores from the repo.

**Comment by zedman2000** [comment]
You should be accessing the cores using instructions from the Zedboard.org website, which will provide you a specific link and specific version of Vivado to use.  That will provide you with a common and tested version of both the IP and Vivado.  We have not tested all combinations and the TIP of the repository does not necessarily have the proper versions of Cores / HDL / TCL for any version of Vivado.

While attempts have been made to accommodate all versions of Vivado, we have only tested the combination listed in the instructions.  That is why the instructions provide specific versions of Vivado / etc.

It is still helpful if you can provide what you are trying to build.

**Comment by bwang40** [comment]
NVM, as I wrote in last mail, I solved the problem. I am only writing that
email to let you know the situation. It is annoying to try with different
vivado and history version of IPs. The version written in the documentation
is also not precise. Hopefully you guys can improve it. Have a good day.
