### ISSUE TITLE
Fluctuating display

### ISSUE THREAD

**Issue by ykkykk001** [Avnet/hdl#4]
We have used Avnet HDMI output (PicoZed Smart Vision Development Kit) on display screen is fluctuating what could be probable reasons behind this problem, based on FMCHC_python_1300 project with external camera interface.
Check demo video of  V_20171205_105538.mp4: http://community.avnet.com/t5/FMC-HDMI-I-O-VITA-Image-Sensor/Fluctuating-display/td-p/18676

**Comment by zedman2000** [comment]
Hi ykkykk001,

We do not monitor this very often.  The best place to go to is the Zedboard forums on E14 and post for assistance.  Those are regularly monitored and can get you the best help the fastest.

https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums

--Dan
