### ISSUE TITLE
Regarding storing 80 bytes of data 

### ISSUE THREAD

**Issue by manojsai17** [Avnet/hdl#8]
We interfaced  slb 9670 with Msp430 16 bit controller through spi which does not support Linux Kernel.

Our Main Task , is store a few bytes of data securely  into SLB 9670  

Now we able to access the spi communication of slb 9670 with controller,

we tested the reading sample  registers of slb 9670   like DIDVID register , version id of slb 9670, status register  and  writing a values  into registers through spi communication.

so spi  read and spi write communication is working  with chip  by accessing this registers.

Our Main Task , is store a few bytes of data into SLB 9670 , so by referring by documents of TCG stack i am not able to understand what steps should i follow to complete our task .

As per documents i am able to understand that we should store data in NV Memory , types of keys and hash algorithms in tpm chip.

so kindly help me at what are required steps , should i follow ?

can you share any documents rather than datasheets  or any libraries from your side to simplify our task?

 thanks for your  support

**Comment by zedman2000** [comment]
Hi there manojsai17,
As you are having trouble that needs troubleshooting, can you please visit the forums on zedboard.org? That would get you the best help. We only really provide GitHub related help through here.

--Dan
