### ISSUE TITLE
fmc imageon script issues

### ISSUE THREAD

**Issue by vonhachtaugust** [Avnet/hdl#9]
Hello!

When running the make_fmc_imageon_gs.tcl in the Vivado 2018.1 tcl client for ZEDBOARD (after updating the ip block minor versions difference between Vivado 2015.4 and Vivado 2018.1 in the fmc_imageon_gs_bd.tcl script) I get the following errors:

ERROR: [DRC NSTD-1] Unspecified I/O Standard: 1 out of 192 logical ports use I/O standard (IOSTANDARD) value 'DEFAULT', instead of a user assigned specific value. This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all I/O standards. This design will fail to generate a bitstream unless all logical ports have a user specified I/O standard value defined. To allow bitstream creation with unspecified I/O standard values (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks NSTD-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run. Problem ports: IO_HDMII_clk_1.

ERROR: [DRC UCIO-1] Unconstrained Logical Port: 1 out of 192 logical ports have no user assigned specific location constraint (LOC). This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all pin locations. This design will fail to generate a bitstream unless all logical ports have a user specified site LOC constraint defined.  To allow bitstream creation with unspecified pin locations (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks UCIO-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run.  Problem ports: IO_HDMII_clk_1.

The port in question is not an accually port but is created after the synt and impl step. The port IO_HDMII_clk exists however and does have valid constraints and I/O standard. The addition of the '_1' in the name (which happens somewhere and I dont know why and where) yields IO_HDMII_clk_1 which in the constraint file is not declared with any set_property specific options (since it is unknown at the constraint creation time) and thus breaks the bitstream generation.

Do you know why and where in the tcl scripts the '_1' is introduced to the name and are there any other reasons for this addition?

/AvH

**Comment by vonhachtaugust** [comment]
Can add that the port is created and attached to a pin during implementation but I cannot find what it is used for or that it even contributes to the design. Thus adding constraints and I/O standard for port IO_HDMII_clk_1 resolves the problem! 

But further down the script new problems with SDK arises and I believe the script needs to be retested with the latest Vivado and SDK versions.

/AvH

**Comment by zedman2000** [comment]
Hi there AvH,
As you are having trouble that needs troubleshooting, can you please visit the forums on zedboard.org?  That would get you the best help.  We only really provide GitHub related help through here.

In the mean time, if the design has not been updated to 2018.x, we recommend to follow through the design by getting the TAG listed in the instructions as well as using the version of Vivado that is called out in the instructions. 

--Dan
